language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"

script:
  - echo "Reached Script Section"
  - gcc   QuotRem.c -o output
  - ./output
  #added section for cunit testing

  - echo "Reached Script Section - C_Unit_Function"
  - gcc   Cunit_Ex.c -o C_Unit_Function -lcunit
  - ./C_Unit_Function
  - size C_Unit_Function
