
language: c



compiler:

  - gcc

before_install:

  - echo "Reached before install Section - cunit packages install"

  - sudo apt-get update

 # - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
 
install:

  - echo  "Reached Install Section"



script:

  - pwd

  - echo "Reached Script Section - Multi File Compile "

  - gcc   	QuotRem.c -o output

  - ./output

  - size output

  - echo "Reached Script Section - cunit_democode"

  - gcc   	QuotRem.c -o cunit_democode -lcunit

  - ./cunit_democode

  - size cunit_democode
